In [6]:
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.patches import Rectangle
from PIL import Image


# --- PROBLEM 1: RGB to CMYK Conversion and Span Check ---

# Define the RGB vectors
rgb_vectors = np.array([
    [1, 0, 0],  # Pure Red
    [0, 1, 0],  # Pure Green
    [0, 0, 1]   # Pure Blue
])

# Compute determinant to check if they span R3
det_rgb = np.linalg.det(rgb_vectors)
print(f"Determinant of RGB matrix: {det_rgb} (Nonzero means they span R3)")

# Function to convert RGB to CMYK
def rgb_to_cmyk(r, g, b):
    k = 1 - max(r, g, b)
    if k == 1:
        return np.array([0, 0, 0, 1])  # Pure black case
    c = (1 - r - k) / (1 - k)
    m = (1 - g - k) / (1 - k)
    y = (1 - b - k) / (1 - k)
    return np.array([c, m, y, k])

# Convert RGB vectors to CMYK
cmyk_vectors = np.array([rgb_to_cmyk(*color) for color in rgb_vectors])
print(f"CMYK Vectors:\n{cmyk_vectors}")

# Compute rank to check if they span R4
rank_cmyk = np.linalg.matrix_rank(cmyk_vectors)
print(f"Rank of CMYK matrix: {rank_cmyk} (Must be 4 to span R4)")

Determinant of RGB matrix: 1.0 (Nonzero means they span R3)
CMYK Vectors:
[[0. 1. 1. 0.]
 [1. 0. 1. 0.]
 [1. 1. 0. 0.]]
Rank of CMYK matrix: 3 (Must be 4 to span R4)
